# Based on Reloaded mod loader's build script

name: Build new Release

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:

  RELOADEDIIMODS: .
  RELOADED_TOOLS_PATH: Tools/Reloaded-Tools

  PUBLISH_BASE: ./Publish

  GITHUB_RELEASE_PATH: ToUpload/Generic
  NUGET_RELEASE_PATH: ToUpload/NuGet

  PUBLISH_CHANGELOG_PATH: CHANGELOG.md

  NUGET_URL: https://api.nuget.org/v3/index.json

  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Setup .NET Core 5.0 # For Reloaded Publisher
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET Core 9.0 # For mods
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 9.0.x

    - name: Unit Tests
      run: |
        dotnet test riri.modutils.Test

    - name: Build Projects
      run: |
        Get-ChildItem -Path . -Directory | ForEach-Object {
            if ($(Get-ChildItem -Path $_.FullName -Filter *.csproj).Count -gt 0 -and !$_.FullName.EndsWith("Test")) {
                dotnet publish $_ -c Release --self-contained false -o "${{ env.PUBLISH_BASE }}/$($_)/${{ env.GITHUB_RELEASE_PATH }}" /p:OutputPath=../${{ env.PUBLISH_BASE}}/$($_)/${{ env.NUGET_RELEASE_PATH }}
                & "C:\Program Files\7-Zip\7z.exe" a -t7z "${{ env.PUBLISH_BASE }}/$($_)/${{ env.GITHUB_RELEASE_PATH }}/$($_).7z" "${{ env.PUBLISH_BASE }}/$($_)/${{ env.GITHUB_RELEASE_PATH }}"
            }
        }
    
    - name: Upload GitHub Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GitHub Release
        path: ${{ env.PUBLISH_BASE }}/*/${{ env.GITHUB_RELEASE_PATH }}/*.7z

    - name: Upload NuGet Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NuGet Release
        path: ${{ env.PUBLISH_BASE }}/*/${{ env.NUGET_RELEASE_PATH }}/*.nupkg

    - name: Upload to GitHub Releases (on Tag)
      uses: softprops/action-gh-release@v0.1.14
      if: env.IS_RELEASE == 'true'
      with:
        body_path: ${{ env.PUBLISH_CHANGELOG_PATH }}
        files: ${{ env.PUBLISH_BASE }}/*/${{ env.GITHUB_RELEASE_PATH }}/*.7z

    - name: Login to NuGet (on Tag)
      uses: NuGet/login@v1
      if: env.IS_RELEASE == 'true'
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: Push to NuGet (on Tag)
      if: env.IS_RELEASE == 'true'
      run: |
        if ([string]::IsNullOrEmpty("${{ steps.login.outputs.NUGET_API_KEY }}"))
        {
          Write-Host "NuGet Repository Key (GitHub Secrets -> NUGET_KEY) Not Specified. Skipping."
          return
        }
        Get-ChildItem -Path Publish -Directory | ForEach-Object {
          Get-ChildItem -Path "${{ env.PUBLISH_BASE }}/$($_)/${{ env.NUGET_RELEASE_PATH }}/$($_)*.nupkg" | ForEach-Object {
            Write-Host "Pushing $($_)"
            dotnet nuget push "$($_)" -k "${{ steps.login.outputs.NUGET_API_KEY }}" -s "${{ env.NUGET_URL }}" --skip-duplicate
          }
        }