# Based on Reloaded mod loader's build script

name: Build new Release

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
  RELEASE_TAG: ${{ github.ref_name }}
  PUBLISH_PATH: ./Publish/Release/
  GITHUB_RELEASE_PATH: ./Publish/Github/
  NUGET_RELEASE_PATH: ./Publish/Nuget/
  CHANGELOG_PATH: ./Publish/Changelog.md
  NUGET_URL: https://api.nuget.org/v3/index.json

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
        # shell: pwsh
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Setup .NET Core SDK (8.0)
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 8.0.x
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Setup AutoChangelog
      run: npm install -g auto-changelog
      
    - name: Create Changelog
      run: |
        [System.IO.Directory]::CreateDirectory("$env:PUBLISH_PATH")
        if ($env:IS_RELEASE -eq 'true') {
            auto-changelog --sort-commits date --hide-credit --template changelog-template.hbs --commit-limit false --starting-version "$env:RELEASE_TAG" --output "$env:CHANGELOG_PATH"
        }
        else {
            auto-changelog --sort-commits date --hide-credit --template changelog-template.hbs --commit-limit false --unreleased --output "$env:CHANGELOG_PATH"
        }

    - name: Build
      run: |
        Remove-Item ${{ env.PUBLISH_PATH }} -Recurse -ErrorAction SilentlyContinue
        New-Item ${{ env.PUBLISH_PATH }} -ItemType Directory -ErrorAction SilentlyContinue
        Remove-Item ${{ env.GITHUB_RELEASE_PATH }} -Recurse -ErrorAction SilentlyContinue
        New-Item ${{ env.GITHUB_RELEASE_PATH }} -ItemType Directory -ErrorAction SilentlyContinue
        Remove-Item ${{ env.NUGET_RELEASE_PATH }} -Recurse -ErrorAction SilentlyContinue
        New-Item ${{ env.NUGET_RELEASE_PATH }} -ItemType Directory -ErrorAction SilentlyContinue
        dotnet restore p3rpc.commonmodutils/p3rpc.commonmodutils.csproj
        dotnet clean p3rpc.commonmodutils/p3rpc.commonmodutils.csproj
        dotnet build p3rpc.commonmodutils/p3rpc.commonmodutils.csproj -c Release -r win-x64 --self-contained false -o ${{ env.PUBLISH_PATH }}
        $include_in_archive = Get-ChildItem -Path ${{ env.PUBLISH_PATH }} -Exclude "*.nupkg"
        Compress-Archive -Path $include_in_archive ${{ env.GITHUB_RELEASE_PATH }}/p3rpc.commonmodutils_${{ github.ref_name }}.zip
        Copy-Item -Path ${{ env.PUBLISH_PATH }}/* -Include "*.nupkg" -Destination ${{ env.NUGET_RELEASE_PATH }} -Recurse
    
    - name: Upload GitHub Release Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: GitHub Release
        path: |
          ${{ env.GITHUB_RELEASE_PATH }}/*

    - name: Upload NuGet Release Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: NuGet Release
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          ${{ env.NUGET_RELEASE_PATH }}/*

    - name: Upload Changelog Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: Changelog
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ env.CHANGELOG_PATH }}
        retention-days: 0

    - name: Upload to GitHub Releases (on Tag)
      uses: softprops/action-gh-release@v0.1.14
      if: env.IS_RELEASE == 'true'
      with:
        body_path: ${{ env.CHANGELOG_PATH }}
        files: |
          ${{ env.GITHUB_RELEASE_PATH }}/*

    - name: Push to NuGet (on Tag)
      env: 
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      if: env.IS_RELEASE == 'true'
      run: |
        if ([string]::IsNullOrEmpty("$env:NUGET_KEY"))
        {
            Write-Host "NuGet Repository Key (GitHub Secrets -> NUGET_KEY) Not Specified. Skipping."
            return
        }
        $items = Get-ChildItem -Path "$env:NUGET_RELEASE_PATH/*.nupkg"
        Foreach ($item in $items)
        {
            Write-Host "Pushing $item"
            dotnet nuget push "$item" -k "$env:NUGET_KEY" -s "$env:NUGET_URL" --skip-duplicate
        }